import Head from 'next/head'
import HeaderMain from "../components/header-main/header-main"
import Hero from "../components/hero/hero"
import SectionSkills from '@/components/section/section-skills'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Just another Software Designer | Cristopher Galarce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/brand/isotype/main.svg" />
				<link rel="mask-icon" href="/img/brand/isotype/main.svg" />
        <meta charSet="utf-8" />
        {/* Mobile behavior */}
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta name="theme-color" content="#000000" />
				<meta name="description" content="Cristopher Galarce is the Product Designer built for your agile teams who will help you to create better products for your users." />
				{/* Apple Homescreen */}
				<meta name="apple-mobile-web-app-title" content="Galarce" />
				<link rel="apple-touch-icon" href="/img/brand/isotype/main-apple.png" />
      </Head>
      <div className='background-sea'>
        <div className='background-main'>
          <div className='background-blur'>
            <div className='layout'>
              <HeaderMain
                navMenu1="Discover"
                navMenu2="How it works"
                navMenu3="Features"
                navMenu4="Contact"
              />
              <Hero />
              <SectionSkills
									h2FirstLine='Ultra powers'
									h2SecondLine='for your project'
									description='Let him work and focus on what matters: business.'
							/>
              <div className='space'></div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
